name: oopanel-dev-package
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: [windows, lv-2020]
    steps:
      - uses: actions/checkout@v3
  test:
    runs-on: [windows, lv-2020]
    needs: [setup]
    steps:
      - dir
  package:
    runs-on: [windows, lv-2020]
    needs: [test]
    steps:
      - dir